# Generated by Django 2.0.5 on 2018-06-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts',
            table=None,
        ),
    ]
